## alertmanager.yml

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by: ["instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "default-notifications"
  routes:
    - receiver: "warning-notifications"
      group_wait: 10s
      matchers:
        - severity="warning"
    - receiver: "critical-notifications"
      group_wait: 10s
      matchers:
        - severity="critical"

receivers:
  - name: "default-notifications"
    discord_configs:
      # Monitoring Alert (Default)
      - webhook_url: "%%AM_DEFAULT_WEBHOOK_URL%%"
        send_resolved: %%AM_DEFAULT_SEND_RESOLVED%% # bool
        title: '{{ template "discord.custom.title" . }}'
        message: '{{ template "discord.custom.message" . }}'

  - name: "warning-notifications"
    discord_configs:
      # Monitoring Alert (Warning)
      - webhook_url: "%%AM_WARNING_WEBHOOK_URL%%"
        send_resolved: %%AM_WARNING_SEND_RESOLVED%% # bool
        title: '{{ template "discord.custom.title" . }}'
        message: '{{ template "discord.custom.message" . }}'

  - name: "critical-notifications"
    discord_configs:
      # Monitoring Alert (Critical)
      - webhook_url: "%%AM_CRITICAL_WEBHOOK_URL%%"
        send_resolved: %%AM_CRITICAL_SEND_RESOLVED%% # bool
        title: '{{ template "discord.custom.title" . }}'
        message: '{{ template "discord.custom.message" . }}'
